import { chromium } from 'playwright';
import { readFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined });
const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
const fixture = await readFile('tests/fixtures/firebase.js', 'utf8');
const bank = '檢驗｜測試';
const q = { questionId: 'q1', question: 'PCR 的 Ct 相差 5，起始量比為何？', options: { A: '5:1', B: '32:1' }, answer: 'B', explanation: '理想倍增下是 2 的 5 次方。', revision: 1 };
await context.addInitScript(({ bank, q }) => { window.__testDatabase = JSON.parse(sessionStorage.getItem('fc-db') || 'null') || { API_KEY: 'test', [bank]: [q], quizCatalog: { [bank]: { count: 1 } }, mistakes: { 'test-user': { [bank]: { first: { ...q, status: 'active', count: 2 }, mastered: { ...q, questionId: 'q2', status: 'mastered', count: 1 } } } } }; }, { bank, q });
await context.route('**/src/services/firebase.js', r => r.fulfill({ contentType: 'text/javascript', body: fixture }));
await context.route(/firebasedatabase|firebaseio|gstatic.com\/firebasejs/, r => r.abort());
let requests = 0, releasePending;
await context.route('https://generativelanguage.googleapis.com/**', async route => {
    requests++;
    if (requests === 3) return new Promise(resolve => { releasePending = async () => { try { await route.fulfill({ status: 503, body: '{}' }); } catch {} resolve(); }; });
    if (requests === 1) return route.fulfill({ status: 503, body: '{}' });
    const request = route.request().postDataJSON(); const sources = JSON.parse(request.contents[0].parts[0].text);
    assert.equal(sources.length, 1); assert.equal(sources[0].questionId, 'q1');
    const card = { front: 'Ct 相差 5 次，理想起始量比為何？', back: '32:1', typingPrompt: 'Ct 相差 5 次，理想起始量比為 ___。', acceptedAnswers: ['32:1', '32 to 1'], explanation: '每次倍增，2⁵ = 32。', sourceIds: ['s1'] };
    return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ candidates: [{ finishReason: 'STOP', content: { parts: [{ text: JSON.stringify({ cards: [card] }) }] } }] }) });
});
const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message)); page.on('dialog', d => d.accept());
const view = page.locator('#flashcardsView');
try {
    await page.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' }); await page.locator('#homeMistakes').click();
    await page.locator('#mistakeView[aria-busy="false"]').waitFor(); await page.locator('#mistakeFlashcardsBtn').click();
    await view.getByRole('button', { name: '重新製作字卡' }).click();
    await view.getByRole('button', { name: 'Learn · 打字填空', exact: true }).waitFor();
    await page.waitForFunction(() => Object.keys(window.__testDatabase.learning?.['test-user'] || {}).some(k => k.startsWith('deck_')));
    await mkdir('artifacts/qa', { recursive: true }); await page.screenshot({ path: 'artifacts/qa/flashcards-deck.png', fullPage: true });
    await view.getByRole('button', { name: '編輯', exact: true }).click();
    await view.getByLabel('字卡集名稱').fill('我的 PCR 字卡');
    await view.getByLabel('正面 · 回想問題').fill('理想 PCR，五次倍增等於幾倍？');
    await view.getByLabel('可接受答案 · 每行一個同義詞').fill('32:1\n32 to 1\n32 倍');
    await view.getByRole('button', { name: '儲存字卡', exact: true }).click();
    await view.getByRole('button', { name: '字卡 · 空白鍵翻面', exact: true }).click();
    assert.equal(await view.locator('.fc-face').innerText(), '理想 PCR，五次倍增等於幾倍？');
    await page.keyboard.press('Space'); assert.equal(await view.locator('.fc-face').innerText(), '32:1');
    await page.keyboard.press('Space'); assert.equal(await view.locator('.fc-ratings').isVisible(), false);
    await view.getByRole('button', { name: '查看答案', exact: true }).click();
    await page.screenshot({ path: 'artifacts/qa/flashcards-flip.png', fullPage: true });
    await view.getByRole('button', { name: '記得了', exact: true }).click();
    await view.getByText('本輪複習完成', { exact: true }).waitFor();
    await view.getByRole('button', { name: '編輯與管理字卡', exact: true }).click();
    await view.getByRole('button', { name: 'Learn · 打字填空', exact: true }).click();
    await view.getByLabel('你的答案').fill('5:1'); await page.keyboard.press('Enter');
    await view.getByRole('heading', { name: '再記一次', exact: true }).waitFor();
    await view.getByRole('button', { name: '下一張', exact: true }).click();
    await view.getByRole('button', { name: '再練不熟的 1 張', exact: true }).click();
    const answer = view.getByLabel('你的答案'); await answer.fill('32 to'); await page.keyboard.press('Space'); await page.keyboard.type('1');
    assert.equal(await answer.inputValue(), '32 to 1'); await page.keyboard.press('Enter');
    await view.getByRole('heading', { name: '答對了', exact: true }).waitFor();
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await view.evaluate(e => e.scrollWidth > e.clientWidth), false);
    await page.screenshot({ path: 'artifacts/qa/flashcards-typing-mobile.png', fullPage: true });
    await page.evaluate(() => document.documentElement.classList.add('dark-mode'));
    assert.equal(await view.evaluate(e => getComputedStyle(e).backgroundColor), 'rgb(32, 33, 36)');
    assert.equal(await view.locator('.fc-stage').evaluate(e => getComputedStyle(e).backgroundColor), 'rgb(36, 38, 41)');
    await page.screenshot({ path: 'artifacts/qa/flashcards-dark-mobile.png', fullPage: true });
    await view.getByRole('button', { name: '下一張', exact: true }).click();
    await page.waitForFunction(() => Object.values(window.__testDatabase.learning['test-user']).some(d => d.cards?.[0]?.reviewCount === 3));
    assert.equal(await page.evaluate(bank => window.__testDatabase.mistakes['test-user'][bank].first.count, bank), 2);
    await page.evaluate(() => { window.__testDatabase.learning['test-user'].card_legacy = { front: '既有筆記問題', back: '舊答案', dueAt: 0, updatedAt: 1 }; sessionStorage.setItem('fc-db', JSON.stringify(window.__testDatabase)); });
    await page.reload({ waitUntil: 'networkidle' }); await page.getByRole('button', { name: '複習卡', exact: true }).click();
    await view.getByRole('heading', { name: '我的 PCR 字卡', exact: true }).waitFor();
    await view.locator('.fc-deck').filter({ hasText: '我的 PCR 字卡' }).getByRole('button', { name: '開啟字卡集', exact: true }).click();
    await view.getByRole('button', { name: '編輯', exact: true }).click(); assert.match(await view.getByLabel('可接受答案 · 每行一個同義詞').inputValue(), /32 倍/);
    await view.getByRole('button', { name: '取消編輯', exact: true }).click();
    await view.getByRole('button', { name: '我的字卡', exact: true }).click();
    await view.locator('.fc-deck').filter({ hasText: '我的筆記字卡' }).getByRole('button', { name: '開啟字卡集', exact: true }).click();
    await view.getByRole('button', { name: 'Learn · 打字填空', exact: true }).click();
    await view.getByText('這組包含舊版筆記字卡，請先編輯並補上填空提示與可接受答案。').waitFor();
    await view.getByRole('button', { name: '編輯', exact: true }).click();
    await view.getByRole('button', { name: '儲存字卡', exact: true }).click();
    await view.getByRole('button', { name: 'Learn · 打字填空', exact: true }).click();
    await view.getByLabel('你的答案').fill('舊答案'); await page.keyboard.press('Enter');
    await view.getByRole('heading', { name: '答對了', exact: true }).waitFor();
    await view.getByRole('button', { name: '下一張', exact: true }).click();
    await view.getByRole('button', { name: '關閉字卡', exact: true }).click();
    await page.locator('#homeMistakes').click();
    await page.locator('#mistakeView[aria-busy="false"]').waitFor();
    const pendingRequest = page.waitForRequest('https://generativelanguage.googleapis.com/**');
    await page.locator('#mistakeFlashcardsBtn').click();
    await view.getByText('正在整理 1 題錯題中的不熟觀念…', { exact: true }).waitFor();
    await pendingRequest;
    await view.getByRole('button', { name: '關閉字卡', exact: true }).click();
    if (releasePending) await releasePending();
    assert.equal(await view.isVisible(), false);
    assert.equal(await page.evaluate(() => Object.keys(window.__testDatabase.learning['test-user']).filter(k => k.startsWith('deck_')).length), 1);
    assert.equal(requests, 3); assert.deepEqual(errors, []);
    console.log('Flashcards passed: notebook scope, AI retry, editing/reload, space flip, typing synonyms, wrong-card retry, mobile/dark mode, isolated review state.');
} finally { await browser.close(); }
